BII_I_1_jsonlite <- jsonlite::read_json(
	fs::path_abs(fs::path_join(c(
		testthat::test_path(), "test-data/ISAdatasets/json/BII-I-1/BII-I-1.json"
	)))
)
BII_S_3_jsonlite <- jsonlite::read_json(
	fs::path_abs(fs::path_join(c(
		testthat::test_path(), "test-data/ISAdatasets/json/BII-S-3/BII-S-3.json"
	)))

)
test_uuid <- uuid::UUIDgenerate()

# Ontology Source References ----
# inv <- Investigation$new()
# inv$from_list(BII_I_1_jsonlite, recursive = TRUE, json = TRUE)
# inv$get_ontology_source_names()
# detecting missing ontology sources
## Roles

# BII_I_1_jsonlite[["people"]][[1]][["roles"]]
# BII_I_1_jsonlite[["studies"]][[1]][["people"]][[1]][["roles"]]

test_that("Study", {
	ts <- Study$new()
	ts$from_list(BII_S_3_jsonlite$studies[[1]])

	expect_equal(ts$submission_date, "2008-08-15")
	expect_equal(ts$public_release_date, "2008-08-15")

	# ts$factors
})

# Person ----
test_that("Person", {
	p1 <- Person$new(`@id` = test_uuid)

	w <- capture_warnings(
		p1$from_list(BII_I_1_jsonlite$people[[1]])
	)
	expect_match(w, "Empty email", all = FALSE)
	expect_match(w, "Found roles with undefined ontology sources", all = FALSE)

	p1 <- Person$new(`@id` = test_uuid)
	expect_warning(
		p1$from_list(BII_S_3_jsonlite[["studies"]][[1]][["people"]][[1]]),
		"Found roles with undefined ontology sources"
	)

	roles <- enumerate_all_roles(BII_I_1_jsonlite)
	expect_true({
		all(purrr::map_lgl(roles, ~checkmate::test_list( # check_list
			.x, len = 3, types = "character",
			names = "named"
			#checkmate::check_subset(c("termAccession", "termSource", "annotationValue"))
		)))
		}
	)

	roles_auto_source <- generate_ontology_source_from_annotation_with_undefined_source(
		annotation_list = roles, source_name =  "RolesOfUndefinedSource",
		source_description = "Roles for Persons which lacked a source for the term",
		comments = list(
			"isar autogenerated" =
			"a source was missing or undefined this generated as a result"
		)
	)
	checkmate::expect_r6(roles_auto_source, classes = "OntologySource")

})


