#' An R6 Object to represent a study from the ISA model
#'
#' study is the central unit, containing information on the subject under study, its characteristics and any treatments applied.
#'
#' @field filename A field to specify the name of the Study file corresponding the definition of that Study.
# #' @field identifier A unique identifier: either a temporary identifier supplied by users or one generated by a repository or other database.
#' @field title A concise phrase used to encapsulate the purpose and goal of the study.
#' @field description A textual description of the study, with components such as objective or goals.
#' @field submission_date The date on which the study was reported to the repository. This should be ISO8601 formatted.
#' @field public_release_date The date on which the study should be released publicly. This should be ISO8601 formatted.
#' @field design_descriptors Classifications of the study based on the overall experimental design.
#' @field publications A list of Publications associated with the Study.
#' @field contacts A list of People/contacts associated with the Study.
#' @field factors A factor corresponds to an independent variable manipulated by the experimentalist with the intention to affect biological systems in a way that can be measured by an assay.
#' @field protocols Protocols used within the ISA artifact.
#' @field assays An Assay represents a portion of the experimental design.
#' @field sources Sources associated with the study, is equivalent to materials sources.
#' @field samples samples associated with the study, is equivalent to materials samples.
#' @field other_material Other Materials associated with the study, is equivalent to materials other_material.
#' @field units A list of Units used in the annotation of material units in the study.
#' @field characteristic_categories Annotations of material characteristics used in the study.
#' @field process_sequence A list of Process objects representing the experimental graphs at the study level.
#' @field comments Comments associated with instances of this class.
#'
#' #field materials Materials associated with the study, contains lists of 'sources', 'samples' and 'other_material'. DEPRECATED.
#' #field graph Graph representation of the study graph.
#'
#' @importFrom R6 R6Class
#'
#' @export
Study <- R6::R6Class(
	"Study",
	public = list(
		filename = '',
		# identifier = '',
		title = character(),
		description = character(),
		submission_date = NULL,
		public_release_date = NULL,
		contacts = NULL,
		design_descriptors = NULL,
		publications = NULL,
		factors = NULL,
		protocols = NULL,
		assays = NULL,
		sources = NULL,
		samples = NULL,
		process_sequence = NULL,
		other_material = NULL,
		characteristic_categories = NULL,
		comments = NULL,
		units = NULL,

		#' @details
		#'
		#' Create a new study object
		#'
		#' @param filename A field to specify the name of the Study file corresponding the definition of that Study.
		# #' @param identifier A unique identifier: either a temporary identifier supplied by users or one generated by a repository or other database.
		#' @param title A concise phrase used to encapsulate the purpose and goal of the study.
		#' @param description A textual description of the study, with components such as objective or goals.
		#' @param submission_date The date on which the study was reported to the repository. This should be ISO8601 formatted.
		#' @param public_release_date The date on which the study should be released publicly. This should be ISO8601 formatted.
		#' @param design_descriptors Classifications of the study based on the overall experimental design.
		#' @param publications A list of Publications associated with the Study.
		#' @param contacts A list of People/contacts associated with the Study.
		#' @param factors A factor corresponds to an independent variable manipulated by the experimentalist with the intention to affect biological systems in a way that can be measured by an assay.
		#' @param protocols Protocols used within the ISA artifact.
		#' @param assays An Assay represents a portion of the experimental design.
		#' @param sources Sources associated with the study, is equivalent to materials sources.
		#' @param samples samples associated with the study, is equivalent to materials \code{[Sample]}.
		#' @param other_material Other Materials associated with the study, is equivalent to materials other_material.
		#' @param units A list of Units used in the annotation of material units in the study.
		#' @param characteristic_categories Annotations of material characteristics used in the study.
		#' @param process_sequence A list of Process objects representing the experimental graphs at the study level.
		#' @param comments Comments associated with instances of this class.
		initialize = function(
			filename = '',
			title = character(),
			description = character(),
			submission_date = NULL,
			public_release_date = NULL,
			contacts = NULL,
			design_descriptors = NULL,
			publications = NULL,
			factors = NULL,
			protocols = NULL,
			assays = NULL,
			sources = NULL,
			samples = NULL,
			process_sequence = NULL,
			other_material = NULL,
			characteristic_categories = NULL,
			comments = NULL,
			units = NULL
		) {
			self$filename <- filename
			if (checkmate::qtest(title, "S[0]")) {
				self$title <- title
			} else {
				self$set_title(title)
			}
			if (checkmate::qtest(description, "S[0]")) {
				self$description <- description
			} else {
				self$set_description(description)
			}
			if (is.null(submission_date)) {
				self$submission_date <- submission_date
			} else {
				self$set_submission_date(submission_date)
			}
			if (is.null(public_release_date)) {
				self$public_release_date <- public_release_date
			} else {
				self$set_public_release_date(public_release_date)
			}
			if(is.null(contacts)) { self$contacts <- contacts } else {
				self$set_contacts(contacts)
			}
			self$design_descriptors <- design_descriptors
			if(is.null(publications)) {
				self$publications <- publications
			} else {
				self$set_publications(publications)
			}
			self$factors <- factors
			self$protocols <- protocols
			self$assays <- assays
			self$sources <- sources
			self$samples <- samples
			self$process_sequence <- process_sequence
			self$other_material <- other_material
			self$characteristic_categories <- characteristic_categories
			self$comments <- comments
			self$units <- units
		},
		#' @details
		#' Check if the title of the study is a string
		#' @param title The title of the study
		check_title = function(title) {
			check <- checkmate::check_string(title, min.chars = 1L)
			error_with_check_message_on_failure(check)
		},
		#' @details
		#' set the title of the study if valid
		#' @param title The title of the study
		set_title = function(title) {
			if (self$check_title(title)) { self$title <- title }
		},
		#' @details
		#' Check if the description of the study is a string
		#' @param description The description of the study
		check_description = function(description) {
			check <- checkmate::check_string(description, min.chars = 1L)
			error_with_check_message_on_failure(check)
		},
		#' @details
		#' set the description of the study if valid
		#' @param description The description of the study
		set_description = function(description) {
			if (self$check_description(description)) { self$description <- description }
		},
		#' @details
		#' Check public_release_date is a Date object
		#' @param public_release_date  a Date Object or ISO8601 formatted data string i.e. YYYY-mm-dd
		check_public_release_date = function(public_release_date) {
			if (is.character(public_release_date)) {
				public_release_date <- as.Date.character(
					public_release_date, tryFormats = c("%Y-%m-%d")
				)
			} else {
				check <- checkmate::check_date(public_release_date)
				error_with_check_message_on_failure(check)
			}
		},
		#' @details
		#' Set public_release_date to a Date object
		#' @param public_release_date a Date Object or ISO8601 formatted data string i.e. YYYY-mm-dd
		set_public_release_date = function(public_release_date) {
			if(self$check_public_release_date(public_release_date)) {
				self$public_release_date <- public_release_date
			}
		},

		#' @details
		#' Check submission_date is a Date object
		#' @param submission_date a Date Object or ISO8601 formatted data string i.e. YYYY-mm-dd
		check_submission_date = function(submission_date) {
			if (is.character(submission_date)) {
				submission_date <- as.Date.character(
					submission_date, tryFormats = c("%Y-%m-%d")
				)
			} else {
				check <- checkmate::check_date(submission_date)
				error_with_check_message_on_failure(check)
			}
		},
		#' @details
		#' Set submission_date to a Date object
		#' @param submission_date a Date Object or ISO8601 formatted data string i.e. YYYY-mm-dd
		set_submission_date = function(submission_date) {
			if(self$check_submission_date(submission_date)) {
				self$submission_date <- submission_date
			}
		},
		#' @details
		#' check contacts is a list of \code{[Person]} objects
		#' @param contacts a list of \code{[Person]} objects
		check_contacts = function(contacts) {
			if(
				checkmate::test_list(contacts, min.len = 1) &&
				all(
					purrr::map_lgl(contacts, ~checkmate::test_r6(.x, "Person"))
				)
			) { return(TRUE) } else {
				stop("All contacts must be Person objects")
			}
		},
		#' @details
		#' check publications is a list of \code{[Publication]} objects
		#' @param publications a list of \code{[Publication]} objects
		check_publications = function(publications) {
			if(
				checkmate::test_list(publications, min.len = 1) &&
				all(purrr::map_lgl(
					publications, ~checkmate::test_r6(.x, "Publication")
				))
			) { return(TRUE) } else {
				stop("All publications must be Publication objects")
			}
		},
		#' @details
		#' Check publications is a list of \code{[Publication]} objects
		#' @param publications a list of \code{[Publication]} objects
		set_publications = function(publications) {
			if (self$check_contacts(publications)) {
				self$publications <- publications
			}
		},
		#' @details
		#' set contacts if contacts is a list of \code{[Person]} objects
		#' @param contacts a list of \code{[Person]} objects
		set_contacts = function(contacts) {
			if (self$check_contacts(contacts)) { self$contacts <- contacts }
		},
		#' @details
		#' checks if comments are a named list of character vectors
		#' @param comments comments
		check_comments = function(comments) { check_comments(comments) },
		#' @details
		#' Sets comments if they are in a valid format
		#' @param comments a list of comments
		set_comments = function(comments) {
			if(self$check_comments(comments)) { self$comments <- comments }
		},
		#' @details
		#' An R list representation of a \code{[Material]} object
		#' @param ld linked data (default FALSE)
		to_list = function(ld = FALSE) {
			study = list(
				"id" = private$id,
				"filename" = self$filename,
				"title" = self$title,
				"description" = self$description,
				"submission_date" = self$submission_date,
				"public_release_date" = self$public_release_date,
				"contacts" = self$contacts$to_list(),
				"design_descriptors" = self$design_descriptors,
				"publications" = self$publications$to_list(),
				"factors" = self$factors$to_list(),
				"protocols" = self$protocols$to_list(),
				"assays" = self$assays$to_list(),
				"sources" = self$sources$to_list(),
				"samples" = self$samples$to_list(),
				"process_sequence" = self$process_sequence$to_list(),
				"other_material" = self$other_material$to_list(),
				"characteristic_categories" = self$characteristic_categories$to_list(),
				"comments" = self$comments,
				"units" = self$units$to_list()
			)
			return(study)
		},
		#' @details
		#' Make \code{[Material]} object from list
		#' @param lst an Material object serialized to a list
		from_list = function(lst) {
			private$id <- lst[["id"]]
			self$filename <- lst[["filename"]]
			self$title <- lst[["title"]]
			self$description <- lst[["description"]]
			self$submission_date <- lst[["submission_date"]]
			self$public_release_date <- lst[["public_release_date"]]
			self$contacts <- lst[["contacts"]]
			self$design_descriptors <- lst[["design_descriptors"]]
			self$publications <- purrr::map(lst[["publications"]], ~{
				p <- Publication$new()
				p$from_list()
				p
			})
			self$factors <- lst[["factors"]]
			self$protocols <- lst[["protocols"]]
			self$assays <- lst[["assays"]]
			self$sources <- lst[["sources"]]
			self$samples <- lst[["samples"]]
			self$process_sequence <- lst[["process_sequence"]]
			self$other_material <- lst[["other_material"]]
			self$characteristic_categories <- lst[["characteristic_categories"]]
			self$comments <- lst[["comments"]]
			self$units <- lst[["units"]]
		},
		#' @details
		#' Get the uuid of this object
		#' @return a uuid
		get_id = function() {
			private$id
		},
		#' @details
		#' set the uuid of this object
		#' @param id a uuid
		#' @param suffix a human readable suffix
		set_id = function(id = uuid::UUIDgenerate(), suffix = character()) {
			private$id <- generate_id(id, suffix)
		}
	),
	private = list(
		id = generate_id()
	)
)

#' identical.Study
#'
#' Allows checking for the identity of \code{[Study]} objects
#'
#' @param x a \code{[Study]} object
#' @param y a \code{[Study]} object
#' @export
identical.Study <- s3_identical_maker(c(
	"filename",
	"title",
	"description",
	"submission_date",
	"public_release_date",
	"contacts",
	"design_descriptors",
	"publications",
	"factors",
	"protocols",
	"assays",
	"sources",
	"samples",
	"process_sequence",
	"other_material",
	"characteristic_categories",
	"comments",
	"units"
))
