ontology_source <- R6Class(
	"ontology_source",
	public = list(
		name = '',
		file = '',
		file_type = '',
		url = '',
		version = '',
		description = '',
		get_terms_list = NULL,
		terms_list = NULL,
		comments = list(),

		initialize = function(
			name = '',
			file = '',
			file_type = '',
			url = '',
			version = '',
			description = '',
			get_terms_list = NULL,
			terms_list = NULL,
			comments = list()
		) {
			self$name <- name
			self$file <- file
			self$file_type <- file_type
			self$url <- url
			self$version <- version
			self$description <- description
			self$comments <- comments
			self$get_terms_list <- get_terms_list

			if(!is.null(terms_list) && !is.null(get_terms_list)) {
				warning(glue::glue(
					.sep = "\n",
					"Both terms_list and get_terms_list are specified.",
					"The manually specified terms list will take precedence over the one generated by the get_terms_list function"
				))
			}

			if (!is.null(terms_list)) {
				self$terms_list <- self$get_terms_list(
					self$file, self$file_type, self$url
				)
			}
		}
	)
)
