
# implement term_validator function instead of term list
# e.g. for a unit a value could be valid if it conforms to a rule
# such as is it an integer?


#' R6 class for the source of ontology terms
#'
#' An \code{ontology_source} describes the resource from which the value of an \code{[ontology_annotation]} is derived from.
#'
#' @field name The name of the source of a term; i.e. the source controlled vocabulary or ontology.
#' @field file A file name or a URI of an official resource.
#' @field file_type the file type, parsable by \code{rdflib::rdf_parse()}
#' @field url ...
#' @field version vesion of the ontology
#' @field description free text description of this source of ontology terms
#' @field get_terms_list function to generate valid terms for file
#' @field terms_list list of valid terms
#' @field comments comments
#'
ontology_source <- R6Class(
	"ontology_source",
	public = list(
		name = '',
		file = '',
		file_type = '',
		url = '',
		version = '',
		description = '',
		get_terms_list = NULL,
		terms_list = NULL,
		comments = list(),

		#' @details
		#'
		#' Create a new [ontology_source] object to act as source for ontology terms
		#'
		#' @param name The name of the source of a term; i.e. the source controlled vocabulary or ontology.
		#' @param file A file name or a URI of an official resource.
		#' @param file_type the file type, parsable by \code{rdflib::rdf_parse()}
		#' @param url ...
		#' @param version vesion of the ontology
		#' @param description free text description of this source of ontology terms
		#' @param get_terms_list function to generate valid terms for file
		#' @param terms_list list of valid terms
		#' @param comments comments
		#'
		initialize = function(
			name = '',
			file = '',
			file_type = '',
			url = '',
			version = '',
			description = '',
			get_terms_list = NULL,
			terms_list = NULL,
			comments = list()
		) {
			self$name <- name
			self$file <- file
			self$file_type <- file_type
			self$url <- url
			self$version <- version
			self$description <- description
			self$comments <- comments
			self$get_terms_list <- get_terms_list

			if (is.null(terms_list) && is.null(get_terms_list)) {
				self$terms_list <- terms_list
				self$get_terms_list <- get_terms_list
			} else {

				if(!is.null(terms_list) && !is.null(get_terms_list)) {
					warning(glue::glue(
						.sep = "\n",
						"Both terms_list and get_terms_list are specified.",
						"The manually specified terms list will take precedence over the one generated by the get_terms_list function"
					))
				}

				if(!is.function(get_terms_list) && is.null(terms_list)) {
					warning(glue::glue(
						.sep = "\n",
						"Please supply either an explicit terms list",
						"where keys are terms and values accessions",
						"or a function which can generate such a list from the",
						"file, file_type, url, & version"
						# !! validate function arguments
					))
				}

				if (is.null(terms_list) && is.function(get_terms_list)) {
					self$terms_list <- self$get_terms_list(
						self$file, self$file_type, self$url, self$version
					)
				}

			}

		},

		#' @details
		#'
		#' make an R list convertible to json
		#'
		#' @param ld (default FALSE)
		to_list = function(ld = FALSE) {
			ontology_source_ref = list(
				name = self$name,
				file =  self$file,
				file_type =  self$file_type,
				url =  self$url,
				version = self$version,
				description = self$description,
				comments = self$comments,
				terms_list = self$terms_list,
				get_terms_list = rawToChar(
					serialize(self$get_terms_list, NULL, ascii = TRUE)
				)
			)
			return(ontology_source_ref)
		},

		#' @details
		#'
		#' Make [ontology_source] from list
		#'
		#' @param lst an ontology source object serialized to a list
		from_list = function(lst) {
			self$name = lst[["name"]]
			self$file = lst[["file"]]
			self$file_type = lst[["file_type"]]
			self$url = lst[["url"]]
			self$version = lst[["version"]]
			self$description = lst[["description"]]
			self$comments = lst[["comments"]]
			self$terms_list = lst[["terms_list"]]
			self$get_terms_list = unserialize(charToRaw(
				lst[["get_terms_list"]]
			))
		}
	)
)
