
# implement term_validator function instead of term list
# e.g. for a unit a value could be valid if it conforms to a rule
# such as is it an integer?

ontology_source <- R6Class(
	"ontology_source",
	public = list(
		name = '',
		file = '',
		file_type = '',
		url = '',
		version = '',
		description = '',
		get_terms_list = NULL,
		terms_list = NULL,
		comments = list(),

		initialize = function(
			name = '',
			file = '',
			file_type = '',
			url = '',
			version = '',
			description = '',
			get_terms_list = NULL,
			terms_list = NULL,
			comments = list()
		) {
			self$name <- name
			self$file <- file
			self$file_type <- file_type
			self$url <- url
			self$version <- version
			self$description <- description
			self$comments <- comments
			self$get_terms_list <- get_terms_list

			if(!is.null(terms_list) && !is.null(get_terms_list)) {
				warning(glue::glue(
					.sep = "\n",
					"Both terms_list and get_terms_list are specified.",
					"The manually specified terms list will take precedence over the one generated by the get_terms_list function"
				))
			}

			if(!is.function(get_terms_list) && is.null(terms_list)) {
				warning(glue::glue(
					.sep = "\n",
					"Please supply either an explicit terms list",
					"where keys are terms and values accessions",
					"or a function which can generate such a list from the",
					"file, file_type, url, & version"
					# !! validate function arguments
				))
			}

			if (!is.null(terms_list) && is.function(get_terms_list)) {
				self$terms_list <- self$get_terms_list(
					self$file, self$file_type, self$url, self$version
				)
			}
		},

		to_list = function(ld = FALSE) {
			ontology_source_ref = list(
				name = self$name,
				file =  self$file,
				version = self$version,
				description = self$description,
				comments = self$comments
			)
			return(ontology_source_ref)
		}
	)
)
