#' An R6 Object to represent a study from the ISA model
#'
#' study is the central unit, containing information on the subject under study, its characteristics and any treatments applied.
#'
#' @field id ...
#' @field filename A field to specify the name of the Study file corresponding the definition of that Study.
#' @field identifier A unique identifier: either a temporary identifier supplied by users or one generated by a repository or other database.
#' @field title A concise phrase used to encapsulate the purpose and goal of the study.
#' @field description A textual description of the study, with components such as objective or goals.
#' @field submission_date The date on which the study was reported to the repository. This should be ISO8601 formatted.
#' @field public_release_date The date on which the study should be released publicly. This should be ISO8601 formatted.
#' @field design_descriptors Classifications of the study based on the overall experimental design.
#' @field publications A list of Publications associated with the Study.
#' @field contacts A list of People/contacts associated with the Study.
#' @field factors A factor corresponds to an independent variable manipulated by the experimentalist with the intention to affect biological systems in a way that can be measured by an assay.
#' @field protocols Protocols used within the ISA artifact.
#' @field assays An Assay represents a portion of the experimental design.
#' @field sources Sources associated with the study, is equivalent to materials['sources'].
#' @field samples samples associated with the study, is equivalent to materials['samples'].
#' @field other_material Other Materials associated with the study, is equivalent to materials['other_material'].
#' @field units A list of Units used in the annotation of material units in the study.
#' @field characteristic_categories Annotations of material characteristics used in the study.
#' @field process_sequence A list of Process objects representing the experimental graphs at the study level.
#' @field comments Comments associated with instances of this class.
#'
#' #field materials Materials associated with the study, contains lists of 'sources', 'samples' and 'other_material'. DEPRECATED.
#' #field graph Graph representation of the study graph.
#'
#' @export
study <- R6Class(
	"study",
	public = list(
		id = '',
		filename = '',
		identifier = '',
		title = '',
		description = '',
		submission_date = '',
		public_release_date = '',
		contacts = NULL,
		design_descriptors = NULL,
		publications = NULL,
		factors = NULL,
		protocols = NULL,
		assays = NULL,
		sources = NULL,
		samples = NULL,
		process_sequence = NULL,
		other_material = NULL,
		characteristic_categories = NULL,
		comments = NULL,
		units = NULL,

		#' @details
		#'
		#' Create a new study object
		#'
		#' @param id ...
		#' @param filename A field to specify the name of the Study file corresponding the definition of that Study.
		#' @param identifier A unique identifier: either a temporary identifier supplied by users or one generated by a repository or other database.
		#' @param title A concise phrase used to encapsulate the purpose and goal of the study.
		#' @param description A textual description of the study, with components such as objective or goals.
		#' @param submission_date The date on which the study was reported to the repository. This should be ISO8601 formatted.
		#' @param public_release_date The date on which the study should be released publicly. This should be ISO8601 formatted.
		#' @param design_descriptors Classifications of the study based on the overall experimental design.
		#' @param publications A list of Publications associated with the Study.
		#' @param contacts A list of People/contacts associated with the Study.
		#' @param factors A factor corresponds to an independent variable manipulated by the experimentalist with the intention to affect biological systems in a way that can be measured by an assay.
		#' @param protocols Protocols used within the ISA artifact.
		#' @param assays An Assay represents a portion of the experimental design.
		#' @param sources Sources associated with the study, is equivalent to materials['sources'].
		#' @param samples samples associated with the study, is equivalent to materials['samples'].
		#' @param other_material Other Materials associated with the study, is equivalent to materials['other_material'].
		#' @param units A list of Units used in the annotation of material units in the study.
		#' @param characteristic_categories Annotations of material characteristics used in the study.
		#' @param process_sequence A list of Process objects representing the experimental graphs at the study level.
		#' @param comments Comments associated with instances of this class.
		initialize = function(
			id = '',
			filename = '',
			identifier = '',
			title = '',
			description = '',
			submission_date = '',
			public_release_date = '',
			contacts = NULL,
			design_descriptors = NULL,
			publications = NULL,
			factors = NULL,
			protocols = NULL,
			assays = NULL,
			sources = NULL,
			samples = NULL,
			process_sequence = NULL,
			other_material = NULL,
			characteristic_categories = NULL,
			comments = NULL,
			units = NULL
		) {
			self$id <- id
			self$filename <- filename
			self$identifier <- identifier
			self$title <- title
			self$description <- description
			self$submission_date <- submission_date
			self$public_release_date <- public_release_date
			self$contacts <- contacts
			self$design_descriptors <- design_descriptors
			self$publications <- publications
			self$factors <- factors
			self$protocols <- protocols
			self$assays <- assays
			self$sources <- sources
			self$samples <- samples
			self$process_sequence <- process_sequence
			self$other_material <- other_material
			self$characteristic_categories <- characteristic_categories
			self$comments <- comments
			self$units <- units
		}
	)
)
